#!/bin/bash

# Получаем список доступных Wi-Fi сетей
networks=$(nmcli -t -f SSID dev wifi list | sed 's/\\:/:/g')

# Отображаем меню с помощью Wofi
chosen_network=$(echo -e "$networks" | wofi --dmenu --prompt "Выберите сеть:" --style ~/.config/wofi/style.css --conf ~/.config/wofi/config)

# Подключаемся к выбранной сети
if [ -n "$chosen_network" ]; then
    nmcli dev wifi connect "$chosen_network"
fi
